### ISSUE TITLE
交叉编译时安装文件的路径不正确

### ISSUE THREAD

**Issue by Yanhao** [linuxdeepin/dtkcore#10]
详见 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924234

我顺便把patch贴在这儿

```diff
--- a/src/dtk_module.prf
+++ b/src/dtk_module.prf
@@ -97,11 +97,10 @@ MODULE_PRI_CONT += \
 write_file($$MODULE_PRI, MODULE_PRI_CONT)|error("Aborting.")
 
 
-QT_HOST_DATA=$$system(qmake -query QT_HOST_DATA)
 qt_module.files = $$MODULE_PRI
 
 isEmpty(MKSPECS_INSTALL_DIR) {
-    MKSPECS_INSTALL_DIR=$${QT_HOST_DATA}/mkspecs
+    MKSPECS_INSTALL_DIR=$$[QT_HOST_DATA]/mkspecs
 }
 qt_module.path = $${MKSPECS_INSTALL_DIR}/modules
 
--- a/src/src.pro
+++ b/src/src.pro
@@ -104,7 +104,7 @@ include(dtk_module.prf)
 prf.files+= $$PWD/*.prf
 
 isEmpty(MKSPECS_INSTALL_DIR) {
-    MKSPECS_INSTALL_DIR=$${QT_HOST_DATA}/mkspecs
+    MKSPECS_INSTALL_DIR=$$[QT_HOST_DATA]/mkspecs
 }
 prf.path = $${MKSPECS_INSTALL_DIR}/features
 ```

**Comment by Yanhao** [comment]
@zccrs

**Comment by zccrs** [comment]
-    MKSPECS_INSTALL_DIR=$${QT_HOST_DATA}/mkspecs
+    MKSPECS_INSTALL_DIR=$$[QT_HOST_DATA]/mkspecs

没看出来这俩有啥改动呀

**Comment by Yanhao** [comment]
好像是没改动，不知道diff是怎么计算差异的，不过这不重要 :p

**Comment by mitya57** [comment]
> 好像是没改动，不知道diff是怎么计算差异的，不过这不重要 :p

This means that you cannot see the difference in the changed lines, right?

However there is difference: I changed curly brackets `{...}` to square brackets `[...]`.

Square brackets allow you to access qmake built-in variables like `QT_HOST_DATA` or `QT_INSTALL_ARCHDATA`. See the documentation: <https://doc.qt.io/qt-5/qmake-language.html#accessing-qmake-properties>.

So your pull request #11 does not actually fix cross-compilation on Debian. To get it working properly, you should use the built-in variables (e.g. `$$[QT_INSTALL_ARCHDATA]`) instead of calling qmake as subprocess.

**Comment by BLumia** [comment]
> So your pull request #11 does not actually fix cross-compilation on Debian. To get it working properly, you should use the built-in variables (e.g. `$$[QT_INSTALL_ARCHDATA]`) instead of calling qmake as subprocess.

@zccrs

**Comment by zccrs** [comment]
@Yanhao @mitya57 https://github.com/linuxdeepin/dtkcore/commit/8d32577a89e54b5c9c834caae83d98e50f59df77

**Comment by mitya57** [comment]
Thanks!
