### ISSUE TITLE
dcapfsfileengine.cpp implementation

### ISSUE THREAD

**Issue by ccmywish** [linuxdeepin/dtkcore#274]
1. `QAbstractFileEngineHandler`
2. `QAbstractFileEngine`
3. `QFSFileEngine` 

are no longer public in Qt. I don't even find their documents.

So `dcapfsfileengine.cpp` and related files seem not easy to implement if we can't rely on Qt's classes.

I have another question:
1. My Qt version is `5.15.6`, I can still compile it. However, I don't know from what version it will be unavailable.

**Comment by ccmywish** [comment]
Generally, this repo lacks `class` comments in each file to quickly let contributors know.

Could you please add more descriptive comments on code rather than doc?

**Comment by ComixHe** [comment]
File engines are not public API since Qt5, it can still be compiled because dtkcore import Qt5::CorePrivate in CMakeLists.txt, until Qt provides CorePrivate as a target for Cmake, it should always be available. In Qt 6.4.2, Qt6::CorePrivate is still provided.
However, it should be noted that the current dcapfsfileengine implementation has bugs, which are planned to be fixed later。

**Comment by ComixHe** [comment]
remove DCapFSFileEngine, see[this pr](https://github.com/linuxdeepin/dtkcore/pull/293).
